#!/bin/sh
set -e -u

premp_root=~/re/premp
render=~/re/premp/scripts/premp-render

bad_argument() {
    printf "Usage: %s: [-r [remote]] type project_name\n" $0
    exit 2
}

# REMOTE=""
# while getopts r: name
# do
#     case $name in
#     r)
#         if [ -z $OPTARG ]
#         then
#             REMOTE=$GIT_REMOTE # default to value of GIT_REMOTE
#         else
#             REMOTE=$OPTARG
#         fi
#         ;;
#     ?)   bad_argument
#         ;;
#     esac
# done
# shift $(($OPTIND - 1))

if [ $# -ne 2 ]
then
    bad_argument
fi

project_type=$1
project_name=$2

echo "Making your $project_type project '$project_name' ..."

mkdir $project_name
cd $project_name

case $project_type in
amsart)
    $render "amsart.tex" $project_name
    $render "SConstruct.Latex" $project_name
    $render ".gitignore.Latex" $project_name
    ;;
pantex)
    $render "pantex.md" $project_name
    $render "Makefile.Pantex" $project_name
    $render ".gitignore.Pantex" $project_name
    cp $premp_root/templates/pandoc-template.tex .
    ;;
esac

git init
git add .
git commit -av -m "Initial commit"

