#!/bin/sh
set -e -u


bad_argument() {
    printf "Usage: %s: [-r [remote]] type project_name\n" $0
    exit 2
}

# REMOTE=""
# while getopts r: name
# do
#     case $name in
#     r)
#         if [ -z $OPTARG ]
#         then
#             REMOTE=$GIT_REMOTE # default to value of GIT_REMOTE
#         else
#             REMOTE=$OPTARG
#         fi
#         ;;
#     ?)   bad_argument
#         ;;
#     esac
# done
# shift $(($OPTIND - 1))

project_type=$1
project_name=$2

if [ -z $project_name ]
then
    bad_argument
fi

echo "Making your $project_type project '$project_name' ..."

mkdir $project_name
cd $project_name

case $project_type in
amsart)
    ~/re/premp/scripts/premp-render "amsart.tex" $project_name
    ~/re/premp/scripts/premp-render "SConstruct.Latex" $project_name
    ~/re/premp/scripts/premp-render ".gitignore.Latex" $project_name
    ;;
esac

